Vagrant.configure("2") do |config|

  # Configure Build server VM
  config.vm.define "build" do |build|
    build.vm.box = "centos/7"

    build.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = "1"
      vb.name = "usp-wm-build-server"
    end

    build.vm.hostname = "usp-wm-build-server"
    build.vm.network "private_network", ip: "192.168.50.4"

    build.vm.provision "shell", privileged: true, path: "bootstrap-centos.sh"

    build.vm.provision :reload
  end

  # Configure test server VM
  config.vm.define "test" do |test|
    test.vm.box = "centos/7"

    test.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = "1"
      vb.name = "usp-wm-test-server"
    end

    test.vm.hostname = "usp-wm-test-server"
    test.vm.network "private_network", ip: "192.168.50.5"

    test.vm.provision "shell", privileged: true, path: "bootstrap-centos.sh"

    test.vm.provision :reload
  end

end
